name: Lint Code with Pylint

on:
  pull_request:
    branches:
      - '**'
    types: [ opened, synchronize, reopened ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    env:
      OVERALL_SCORE_LIMIT: 8.0
      CHANGED_SCORE_LIMIT: 8.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip          
          pip install pylint

      - name: Run pylint on entire project
        id: pylint_project
        run: |
          echo "Starting pylint check on ./src"
          echo "Current local path:"
          pwd
          
          echo "Listing contents of the current directory:"
          ls -la

          pylint ./src > pylint_report.txt || true
          echo "Pylint check completed, report saved to pylint_report.txt"
          
          echo "Calculating pylint score..."
          pylint_score=$(pylint --exit-zero ./src | tail -n 2 | grep -oE '[0-9]+\.[0-9]+/10' | head -n 1 | cut -d '/' -f 1)
          echo "Pylint score calculated: $pylint_score"
          
          echo "Setting pylint score output..."
          echo "project_score=$pylint_score" >> $GITHUB_ENV

      - name: Get list of modified Python files
        id: modified_files
        run: |
          echo "Fetching modified Python files..."
          modified_files=$(git diff --name-only ${{ github.sha }} | grep '.py$' | tr '\n' ' ')
          echo "files=$modified_files" >> $GITHUB_ENV

      - name: Run pylint on modified files
        if: steps.modified_files.outputs.files != ''
        id: pylint_modified
        run: |
          pylint ${{ steps.modified_files.outputs.files }} > pylint_modified_report.txt || true
          pylint_score=$(pylint --exit-zero ${{ steps.modified_files.outputs.files }} | tail -n 2 | grep -oE '[0-9]+\.[0-9]+/10' | head -n 1 | cut -d '/' -f 1)
          echo "Pylint score for modified files: $pylint_score"
          echo "modified_score=$pylint_score" >> $GITHUB_ENV

      - name: Upload pylint report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pylint-report
          path: |
            pylint_report.txt
            pylint_modified_report.txt

      - name: Evaluate pylint scores
        run: |
          echo "Evaluating pylint score for the entire project..."
          if (( $(echo "$PROJECT_SCORE < $OVERALL_SCORE_LIMIT" | bc -l) )); then
            echo "Pylint score is below $OVERALL_SCORE_LIMIT: $PROJECT_SCORE"
            exit 1
          else
            echo "Pylint score is acceptable: $PROJECT_SCORE"
          fi

          echo "Evaluating pylint score for modified files..."
          if (( $(echo "$MODIFIED_SCORE < $CHANGED_SCORE_LIMIT" | bc -l) )); then
            echo "Pylint score for modified files is below $CHANGED_SCORE_LIMIT: $MODIFIED_SCORE"
            exit 1
          fi
