name: Lint Code with Pylint

on:
  pull_request:
    branches:
      - '**'
    types: [ opened, synchronize, reopened ]

env:
  PYLINT_THRESHOLD: 8.0

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip          
          python3 -m pip install -r requirements.txt

      - name: Set PYTHONPATH environment variable
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}/src" >> $GITHUB_ENV
        shell: bash

      - name: print PYTHONPATH env variable
        run: echo $PYTHONPATH
        shell: bash

      - name: Run pylint on entire project
        id: pylint_project
        run: |
          echo "Starting pylint check on ./src"
          pylint ./src > pylint_report.txt || true
          
          echo "Pylint report:"
          cat pylint_report.txt

      - name: Extract pylint score from report
        id: extract_pylint_score
        run: |
          pylint_score=$(tail -n 2 pylint_report.txt | grep -oE '[0-9]+\.[0-9]+/10' | head -n 1 | cut -d '/' -f 1)
          echo "Pylint score calculated: $pylint_score"
          echo "pylint_score=$pylint_score" >> $GITHUB_ENV

      - name: Check pylint score
        env:
          pylint_score: ${{ env.pylint_score }}
        run: |
          if (( $(echo "$pylint_score < ${{ env.PYLINT_THRESHOLD }}" | bc -l) )); then
            echo "Pylint score is below ${{ env.PYLINT_THRESHOLD }}: $pylint_score"
            exit 1
          else
            echo "Pylint score is acceptable: $pylint_score"
          fi
